repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^backend/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.1
    hooks:
      - id: eslint
        files: ^frontend/src/.*\.(ts|tsx)$
        additional_dependencies:
          - eslint@8.57.0
          - typescript@5.5.4
